### ISSUE TITLE
给您添麻烦了 想问下 我复现您的模型f一直是0，没有动过代码，不知道是不是我哪里遗漏了，您能帮我看一下吗？

### ISSUE THREAD

**Issue by 2019hong** [SL-Stone/ERE-20210518#1]
我实在太菜了，之前跑了casrel但一直不会改，看到您的代码和模型对我帮助非常大，但是尝试复现F值却一直是零。您能帮我看看大概是哪里不对吗？

**Comment by 2019hong** [comment]
![Uploading 1623375715(1).png…]()

**Comment by 2019hong** [comment]
![1623375715(1)](https://user-images.githubusercontent.com/54787403/121618614-a6ab8e00-ca99-11eb-867d-e2ae27df21cd.png)

**Comment by 2019hong** [comment]
![image](https://user-images.githubusercontent.com/54787403/121618672-c478f300-ca99-11eb-9958-8007fdcdc6c5.png)

**Comment by 2019hong** [comment]
我在第20个轮次收获了0.488的F值

**Comment by SL-Stone** [comment]
@2019hong 您好，感谢您对我的项目的关注！
我在GitHub上的描述没有涉及太多细节，对您提及的问题作以下回复：
F1值增加得慢是学习率太低造成的，可以把学习率LR的值设的大一点。
本文模型的F1最佳性能是在runG.py上得到的。迭代35个周期，期间调整过学习率和批大小。开始训练时batch size为6，学习率为1e-3，最后5个周期的batch size为8，学习率为1e-4。在runG.py中显示的LR和BATCH_SIZE值是在F1达到0.758之后调整的，但是由于ddl时间的缘故，所有没有继续进行训练。您可以根据自己的想法设置这两个参数。
本文模型有很多可以提升的空间，欢迎交流！

**Comment by 2019hong** [comment]
@SL-Stone 感谢您的回复！！我会把学习率调高一点，然后尝试进行调参~谢谢您！！！
