### ISSUE TITLE
还想问您一下，runG_all文件中train_triples1.json等文件是如何生成的？打扰您了

### ISSUE THREAD

**Issue by 2019hong** [SL-Stone/ERE-20210518#2]
![image](https://user-images.githubusercontent.com/54787403/121637759-7a553900-cabc-11eb-97d2-7f8df2705980.png)

**Comment by SL-Stone** [comment]
@2019hong 关于train_triples1.json等文件是对train_triples.json的复制，还有其他的xxx_triples1.json都是对xxx_triples.json的复制，以及output1.json同理。因为实验时同时运行多个模型，出现过问题，所以为了防止文件访问冲突（尽管理论上读文件不会冲突，保险起见），复制了文件。后来发现是Linux的CPU核的问题，发现一个核只会跑一个Python程序。如果您对这方面有自己的见解，感谢分享。
我对程序进行修改和整理。统一使用xxx_triples.json. 删去了1。感谢您的提问。

**Comment by 2019hong** [comment]
@SL-Stone 前几天一直有点忙，今天才看到您回复了我~！谢谢您！！
我会再好好学习下您的代码~~给您添麻烦了
